@baseUrl=http://localhost:3000/api

@resourceName=products

#Products

# @name getAll
GET {{baseUrl}}/{{resourceName}}

###

# @name filterProductsPrice
GET {{baseUrl}}/{{resourceName}}?price_gte=100

###

# @name filterProductsName
GET {{baseUrl}}/{{resourceName}}?name_like=Unbranded 

###

# @name pagination
GET {{baseUrl}}/{{resourceName}}?_page=1&_limit=4

###

# @name sort
GET {{baseUrl}}/{{resourceName}}?_sort=price&_order=asc

###

# @name addNew
POST {{baseUrl}}/{{resourceName}}
Content-Type: application/json

{
    "categoryId": "106f394d-acdc-4713-b07c-dbd029c448b0",
    "name": "Unbranded Cotton Chicken",
    "color": "lavender",
    "price": 610,
    "description": "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
    "thumbnailUrl": "http://placeimg.com/400/400"
}

###

# @name update
PATCH {{baseUrl}}/{{resourceName}}/Od-48pu
Content-Type: application/json

{
    "name": "Unbranded Cotton Chicken Update",
    "color": "red",
    "price": 800
}

###

# @name remove
DELETE http://localhost:3000/api/{{resourceName}}/2